// <auto-generated />
using System;
using Covid19Tracking;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Covid19Tracking.Migrations
{
    [DbContext(typeof(CovidDbContext))]
    [Migration("20201115221805_FKChanges")]
    partial class FKChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Covid19Tracking.Citizen", b =>
                {
                    b.Property<int>("SSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("MunicipalityID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.Property<int>("age")
                        .HasColumnType("INTEGER");

                    b.HasKey("SSN");

                    b.HasIndex("MunicipalityID");

                    b.ToTable("Citizen");
                });

            modelBuilder.Entity("Covid19Tracking.CitizenLocation", b =>
                {
                    b.Property<int>("SSN")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Addr")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.HasKey("SSN");

                    b.HasIndex("Addr");

                    b.ToTable("CitizenLocation");
                });

            modelBuilder.Entity("Covid19Tracking.Location", b =>
                {
                    b.Property<string>("Addr")
                        .HasColumnType("TEXT");

                    b.Property<int>("MunicipalityID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Addr");

                    b.HasIndex("MunicipalityID");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("Covid19Tracking.Municipality", b =>
                {
                    b.Property<int>("MunicipalityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Population")
                        .HasColumnType("INTEGER");

                    b.Property<string>("mName")
                        .HasColumnType("TEXT");

                    b.Property<string>("nName")
                        .HasColumnType("TEXT");

                    b.HasKey("MunicipalityID");

                    b.HasIndex("nName");

                    b.ToTable("Municipality");
                });

            modelBuilder.Entity("Covid19Tracking.Nation", b =>
                {
                    b.Property<string>("nName")
                        .HasColumnType("TEXT");

                    b.HasKey("nName");

                    b.ToTable("Nation");
                });

            modelBuilder.Entity("Covid19Tracking.TestCenter", b =>
                {
                    b.Property<int>("CenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hours")
                        .HasColumnType("TEXT");

                    b.Property<int>("MunicipalityID")
                        .HasColumnType("INTEGER");

                    b.HasKey("CenterId");

                    b.HasIndex("MunicipalityID");

                    b.ToTable("Testcenter");
                });

            modelBuilder.Entity("Covid19Tracking.TestCenterManagement", b =>
                {
                    b.Property<int>("manageID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<int>("phoneNum")
                        .HasColumnType("INTEGER");

                    b.HasKey("manageID");

                    b.ToTable("Testcentermanagement");
                });

            modelBuilder.Entity("Covid19Tracking.TestedAt", b =>
                {
                    b.Property<int>("SSN")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestedAtID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<bool>("result")
                        .HasColumnType("INTEGER");

                    b.Property<string>("status")
                        .HasColumnType("TEXT");

                    b.HasKey("SSN");

                    b.HasIndex("TestedAtID");

                    b.ToTable("TestedAt");
                });

            modelBuilder.Entity("Covid19Tracking.Citizen", b =>
                {
                    b.HasOne("Covid19Tracking.Municipality", "municipality")
                        .WithMany("citizens")
                        .HasForeignKey("MunicipalityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("municipality");
                });

            modelBuilder.Entity("Covid19Tracking.CitizenLocation", b =>
                {
                    b.HasOne("Covid19Tracking.Location", "location")
                        .WithMany("citizenLocations")
                        .HasForeignKey("Addr");

                    b.HasOne("Covid19Tracking.Citizen", "citizen")
                        .WithMany("citizenLocations")
                        .HasForeignKey("SSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("citizen");

                    b.Navigation("location");
                });

            modelBuilder.Entity("Covid19Tracking.Location", b =>
                {
                    b.HasOne("Covid19Tracking.Municipality", "municipality")
                        .WithMany("locations")
                        .HasForeignKey("MunicipalityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("municipality");
                });

            modelBuilder.Entity("Covid19Tracking.Municipality", b =>
                {
                    b.HasOne("Covid19Tracking.Nation", "nation")
                        .WithMany("municipalities")
                        .HasForeignKey("nName");

                    b.Navigation("nation");
                });

            modelBuilder.Entity("Covid19Tracking.TestCenter", b =>
                {
                    b.HasOne("Covid19Tracking.Municipality", "municipality")
                        .WithMany("testCenters")
                        .HasForeignKey("MunicipalityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("municipality");
                });

            modelBuilder.Entity("Covid19Tracking.TestCenterManagement", b =>
                {
                    b.HasOne("Covid19Tracking.TestCenter", "testCenter")
                        .WithOne("testCenterMangement")
                        .HasForeignKey("Covid19Tracking.TestCenterManagement", "manageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("testCenter");
                });

            modelBuilder.Entity("Covid19Tracking.TestedAt", b =>
                {
                    b.HasOne("Covid19Tracking.Citizen", "citizen")
                        .WithMany("testedAts")
                        .HasForeignKey("SSN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Covid19Tracking.TestCenter", "testCenter")
                        .WithMany("testedAts")
                        .HasForeignKey("TestedAtID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("citizen");

                    b.Navigation("testCenter");
                });

            modelBuilder.Entity("Covid19Tracking.Citizen", b =>
                {
                    b.Navigation("citizenLocations");

                    b.Navigation("testedAts");
                });

            modelBuilder.Entity("Covid19Tracking.Location", b =>
                {
                    b.Navigation("citizenLocations");
                });

            modelBuilder.Entity("Covid19Tracking.Municipality", b =>
                {
                    b.Navigation("citizens");

                    b.Navigation("locations");

                    b.Navigation("testCenters");
                });

            modelBuilder.Entity("Covid19Tracking.Nation", b =>
                {
                    b.Navigation("municipalities");
                });

            modelBuilder.Entity("Covid19Tracking.TestCenter", b =>
                {
                    b.Navigation("testCenterMangement");

                    b.Navigation("testedAts");
                });
#pragma warning restore 612, 618
        }
    }
}
